package br.com.andrelima.projetologin;

import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class ComumTela extends javax.swing.JFrame {

    /**
     * Creates new form ComumTela
     */
    public ComumTela() {
        initComponents();
        setLocationRelativeTo(null);

        // Nomes das colunas
        String[] columnNames = {"Evento", "Data", "Endereço", "Telefone", "E-mail"};

        // Dados para popular a tabela
        Object[][] data = {
            {"Evento Cultural", "15/03/2024", "Rua Taquari, 812", "11994226232", "ana@gmail.com"},
            {"Conferência de Tecnologia", "20/04/2024", "Av. Paulista, 012", "11987654321", "joao@gmail.com"},
            {"Festival de Música", "10/05/2024", "Rua Augusta, 732", "11912345678", "carlos@gmail.com"},
            {"Feira de Arte", "06/05/2024", "Av. Rebouças, 67", "11955555555", "maria@gmail.com"},
            {"Seminário de Negócios", "07/12/2024", "Rua Oscar Freire, 94", "11944444444", "pedro@gmail.com"},
            {"Exposição de Fotografia", "18/08/2024", "Av. Faria Lima, 690", "11933333333", "lucas@gmail.com"},
            {"Encontro de Gastronomia", "2/09/2024", "Rua Haddock Lobo, 500", "11922222222", "patricia@gmail.com"},
            {"Congresso de Educação", "10/05/2024", "Rua Bela Cintra, 345", "11911111111", "fernanda@gmail.com"},
            {"Desfile de Moda", "15/11/2024", "Rua Oscar Freire, 007", "11900000000", "roberta@gmail.com"},
            {"Festival de Cinema", "12/10/2024", "Av. Paulista, 654", "11888888888", "marcelo@gmail.com"},
            {"Feira de Livros", "25/01/2024", "Av. Rio Branco, 879", "1187654321", "livraria@gmail.com"},
            {"Exposição de Arte Moderna", "15/02/2024", "Rua dos Artistas, 874", "11987654321", "moderna@gmail.com"},
            {"Simpósio de Medicina", "20/03/2024", "Av. 9 de Julho, 090", "1196543210", "medicina@gmail.com"},
            {"Semana de Moda", "04/05/2024", "Rua das Grifes, 745", "1190987654", "fashion@gmail.com"},
            {"Conferência de Ciência e Tecnologia", "28/05/2024", "Av. das Inovações, 543", "1191122334", "science@gmail.com"},
            {"Mostra de Cinema Internacional", "06/10/2024", "Av. dos Cinéfilos, 019", "1193344556", "cinema@gmail.com"},
            {"Festival de Gastronomia Italiana", "18/07/2024", "Rua da Pizza,074", "1195566778", "italianfood@gmail.com"},
            {"Exposição de Carros Antigos", "2/08/2024", "Av. das Relíquias, 645", "1198899000", "carrosantigos@gmail.com"},
            {"Concerto de Música Clássica", "09/05/2024", "Rua dos Maestros,123", "1190011223", "classicalmusic@gmail.com"},
            {"Feira de Tecnologia", "30/10/2024", "Av. dos Gadgets, 765", "1193344556", "tecnologia@gmail.com"}
        };

       // Criando o modelo de tabela personalizado com os dados e nomes das colunas
        DefaultTableModel model = new DefaultTableModel(data, columnNames);

        // Criando a tabela
        JTable table = new JTable(model);

        // Definindo o renderizador de células para a coluna de datas
        table.getColumnModel().getColumn(1).setCellRenderer(new DateCellRenderer());

        // Adicionando a tabela a um JScrollPane
        jScrollPane1.setViewportView(table);

    }

    /**
     * Custom cell renderer for formatting dates with slashes.
     */
    private class DateCellRenderer extends DefaultTableCellRenderer {
        private SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        @Override
        public void setValue(Object value) {
            if (value instanceof Date) {
                value = formatter.format(value);
            }
            super.setValue(value);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Evento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabela de eventos");
        setResizable(false);

        Evento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evento", "Data", "Endereço", "Telefone", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Evento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1228, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComumTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComumTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComumTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComumTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComumTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable Evento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
